#!/usr/bin/env bash
# It configures an Nginx server to listen on port 80

# removes the default Nginx configuration files
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80 for all active IPv4 IPs
In -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
