#!/usr/bin/env bash
# It configures an Nginx server to listen on port 80

# It creates a symbolic link (-s option) between the Nginx configuration file
# and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx start
service nginx start
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
