#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but of the
# 9th iteration, + displays Best School and then Hi on a new line
m=0
while(("$m" < 10));
do
	echo "Best School"
	if (("$m" == 8))
	then
		echo "Hi"
	fi
	((m++))
done
