#!/usr/bin/env bash
# write a Bash script that displays the time for 12 hours and 59 minutes
# displays hours from 0 to 12
# displays minutes from 1 to 59
m=0
i=1
while ((m <= 12));
do
	echo "Hour: $m"

	while ((i <= 59));
	do
		echo "$i"
		((i++))
	done

	i=1
	((m++))
done
