#!/usr/bin/env bash
# write a Bash script that displays the content of
# the working directory in a list format
# Where only the part of the name after the first dash is displayed

m=0
for m in *;
do
	if [[ "$m" == .* ]];
	then
		continue;
	fi

	remove_dash="${m#*-}"

	echo "$remove_dash"
done
